# Generated by Django 5.0 on 2023-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_item',
            field=models.CharField(choices=[('P', 'People'), ('W', 'Watches'), ('CM', 'Cinema'), ('CH', 'Clothes'), ('H', 'Home items'), ('A', 'Animals')], default='p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label_item',
            field=models.CharField(choices=[('S', 'success'), ('P', 'primary'), ('D', 'danger')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
