# Generated by Django 5.0 on 2023-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_item_category_item_item_label_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug_item',
            field=models.SlugField(default='teste-item'),
            preserve_default=False,
        ),
    ]
